### PR TITLE
Removed default values for features specified

### LINKED ISSUE #65: Can't clear "Specified Features"
The new "Specified Features" setting defaults to "test", and it is impossible to clear it. If you leave the field blank, Atom resets it to the default of "test" again. Cargo fails when passed nonexistent `--features` arguments, and linter-rust silently ignores the failure and reports "No Errors".

### PR DESCRIPTION
**Pull request by White-Oak**
Removed default values for features specified and added back `lint test code` option.

Also added a check to stderr handler if there is a message about invalid features specified.

Fixes #65.

### CODE REVIEW

File: lib/linter-rust.coffee [hunk 1]
```diff
@@ -30,6 +30,11 @@ class LinterRust
       stdout = (data) ->
         console.log data if do atom.inDevMode
       stderr = (err) ->
+        if err.indexOf('does not have these features')
+          atom.notifications.addError "Invalid specified features",
+            detail: "#{err}"
+            dismissable: true
+          handle()
```
Comment (gmist) [inline lib/linter-rust.coffee]: #67
