### PR TITLE
Fixed the way json errors are requested from cargo & rustc

### LINKED ISSUE #69: Invalid arguments when using rust 1.13 (nightly)
Updated rust today, and got an invalid arguments error. Looking into this it seems cargo has a problem with the `-- --error-format=json` part. Asking in the #rust channel it seems this was never an accepted way to pass commands to rustc via cargo. Using the rustc option however will result in "invalid specified features" errors being spammed for every line of output given from cargo.

### PR DESCRIPTION
**Pull request by White-Oak**
Closes #69

Also fixed the way envinronment variables were passed to BufferedProcess --
according to [the documentation](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback) (*`BufferedProcess` is actually a wrapper above node's exec*) 
they should be passed in an `env` subobject of `options`, but they were passed 'as is' in the options object.
Adding to these environment variables accordingly set `RUSTFLAGS` variable, when JSON errors are available, makes cargo tell compiler to output JSON errors.
When using `rustc` simply providing `--error-format=json` is enough to make compiler do what we want.

### CODE REVIEW

**Comment by White-Oak** [comment]
Ah, I've also added the code to always redirect errors to Atom from `stderr` when Atom is run in dev mode.

File: lib/linter-rust.coffee [hunk 1]
```diff
@@ -21,8 +21,9 @@ class LinterRust
       file = @initCmd do textEditor.getPath
       curDir = path.dirname file
       PATH = path.dirname @cmd[0]
-      options = JSON.parse JSON.stringify process.env
-      options.PATH = PATH + path.delimiter + options.PATH
+      options = new Object
```
Comment (Arcanemagus) [inline lib/linter-rust.coffee]: Any reason you didn't just use `{}`?

File: lib/linter-rust.coffee [hunk 2]
```diff
@@ -49,6 +55,9 @@ class LinterRust
         else
           resolve []
 
+      if do @ableToJSONErrors
```
Comment (Arcanemagus) [inline lib/linter-rust.coffee]: Since this is now being called _three_ times for every lint call, it's results should probably be cached...

File: lib/linter-rust.coffee (hunk 1 above)
Comment (White-Oak) [inline lib/linter-rust.coffee]: @Arcanemagus the only reason for this is my poor knowledge of CoffeeScript :) I'll fix this.

File: lib/linter-rust.coffee [hunk 3]
```diff
@@ -34,6 +35,11 @@ class LinterRust
           atom.notifications.addError "Invalid specified features",
             detail: "#{err}"
             dismissable: true
+        else
+          if do atom.inDevMode
+            atom.notifications.addError "Something wrong",
```
Comment (Arcanemagus) [inline lib/linter-rust.coffee]: "Something went wrong" (running rustc?)

File: lib/linter-rust.coffee (hunk 1 above)
Comment (Arcanemagus) [inline lib/linter-rust.coffee]: Yea, every time I see linters still stuck on CoffeeScript I cringe, I'll get to moving them to ES2015 eventually! 😛.

**Comment by Arcanemagus** [comment]
That's all I see just looking at the code.

File: lib/linter-rust.coffee (hunk 1 above)
Comment (Arcanemagus) [inline lib/linter-rust.coffee]: http://decaffeinate-project.org/repl/

^ This is great for getting readable code out of the CoffeeScript

File: lib/linter-rust.coffee (hunk 2 above)
Comment (White-Oak) [inline lib/linter-rust.coffee]: @Arcanemagus I'll cache it for a single linter usage (meaning per-`lint` call), but I think it would be incorrect to cache it globally (I mean for a duration of Atom running) -- a user may switch between versions of rustc, while still using the same Atom process running).

File: lib/linter-rust.coffee (hunk 3 above)
Comment (White-Oak) [inline lib/linter-rust.coffee]: @Arcanemagus is it a proposal for a better error message? If yes, that sounds good, I'll fix it.

**Comment by White-Oak** [comment]
@Arcanemagus I've added a cache for 'ability to have JSON errors', fixed 'new object' stuff and the way dev mode notifications look:
dev mode notifications

It is possible to stack them in one error message, if one would prefer it that way.

**Comment by Arcanemagus** [comment]
As it's already behind a dev mode check, it's probably fine to leave them like that.

File: lib/linter-rust.coffee [hunk 4]
```diff
@@ -21,11 +22,14 @@ class LinterRust
...
       PATH = path.dirname @cmd[0]
-      options = JSON.parse JSON.stringify process.env
-      options.PATH = PATH + path.delimiter + options.PATH
+      options =
+        env: JSON.parse JSON.stringify process.env
+      options.env.PATH = PATH + path.delimiter + options.env.PATH
       options.cwd = curDir
       command = @cmd[0]
       args = @cmd.slice 1
+      @cachedAbleToJsonErrors = null
```
Comment (gmist) [inline lib/linter-rust.coffee]: hmm... is this line really necessary?

Comment (White-Oak) [inline lib/linter-rust.coffee]: @gmist This ensures that the cached value is live only for a one lint process.

Comment (gmist) [inline lib/linter-rust.coffee]: Ah, exactly
