### PR TITLE
Fix #36

### LINKED ISSUE #36: Failed to run cargo
Linter says `spawn cargo ENOENT`.

### PR DESCRIPTION
**Pull request by andrewrynhard**
This adds the parent directory of the rustc installation to the PATH of the
spawned command. Otherwise cargo does not know where rustc is installed.

### CODE REVIEW

File: lib/linter-rust.coffee [hunk 1]
```diff
@@ -108,6 +111,17 @@ class LinterRust
       directory = path.resolve path.join(directory, '..')
     return false
 
+  makeOpts: (PATH) ->
+    options = process.env;
 
+    switch process.platform
+      when "darwin" || "linux"
```
Comment (gmist) [inline lib/linter-rust.coffee]: Why not just use [path.delimiter](https://nodejs.org/api/path.html#path_path_delimiter)?

**Comment by andrewrynhard** [comment]
@gmist: Good point. Using that now and also fixed the PATH.

File: lib/linter-rust.coffee [hunk 2]
```diff
@@ -17,6 +17,9 @@ class LinterRust
       results = []
       file = @initCmd do textEditor.getPath
       curDir = path.dirname file
+      PATH = path.dirname @cmd[0]
+      options = @makeOpts(PATH)
+      options.cwd = curDir
       @cmd.push file
       command = @cmd[0]
       options = {cwd: curDir}
```
Comment (gmist) [inline lib/linter-rust.coffee]: I think that here the variable ```options``` will be overwritten and all previous steps do not make sense.

Comment (andrewrynhard) [inline lib/linter-rust.coffee]: @gmist: yes you are correct. I pushed a fix again. Sorry. To answer your question about the switch statement. I guess this was just a habit. I once faced an issue with using PATH vs Path on win32 platforms. But after double checking again just now it doesn't seem to be an issue.

**Comment by gmist** [comment]
Thanks!
